### ISSUE TITLE
codedoc check crashes

### ISSUE THREAD

**Issue by TysonMN** [CONNECT-platform/codedoc-cli#4]
This is what happens when I run `codedoc check` in [my blog](https://github.com/bender2k14/tyson-williams-blog):
```
twilliams@EDMONDS MINGW64 /c/Code/Blogs/tyson-williams-blog (master)
$ codedoc check

# Checking CODEDOC configuration ...

# Checking Title configuration ...

C:\Users\twilliams\AppData\Roaming\npm\node_modules\@codedoc\cli\node_modules\typescript\lib\typescript.js:139175
                var error = new Error("Could not find source file: '" + fileName + "'.");
                            ^
Error: Could not find source file: 'C:/Code/Blogs/tyson-williams-blog/{'.
    at getValidSourceFile (C:\Users\twilliams\AppData\Roaming\npm\node_modules\@codedoc\cli\node_modules\typescript\lib\typescript.js:139175:29)
    at Object.getEmitOutput (C:\Users\twilliams\AppData\Roaming\npm\node_modules\@codedoc\cli\node_modules\typescript\lib\typescript.js:139560:30)
    at getOutput (C:\Users\twilliams\AppData\Roaming\npm\node_modules\@codedoc\cli\node_modules\ts-node\src\index.ts:562:32)
    at Object.compile (C:\Users\twilliams\AppData\Roaming\npm\node_modules\@codedoc\cli\node_modules\ts-node\src\index.ts:775:32)
    at _eval (C:\Users\twilliams\AppData\Roaming\npm\node_modules\@codedoc\cli\node_modules\ts-node\src\bin.ts:321:22)
    at evalAndExit (C:\Users\twilliams\AppData\Roaming\npm\node_modules\@codedoc\cli\node_modules\ts-node\src\bin.ts:296:14)
    at main (C:\Users\twilliams\AppData\Roaming\npm\node_modules\@codedoc\cli\node_modules\ts-node\src\bin.ts:224:5)
    at Object.<anonymous> (C:\Users\twilliams\AppData\Roaming\npm\node_modules\@codedoc\cli\node_modules\ts-node\src\bin.ts:513:3)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
(node:984) UnhandledPromiseRejectionWarning: undefined
(node:984) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:984) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by loreanvictor** [comment]
@bender2k14 ok I cannot replicate the same issue on your repo on my own machine, so I suspect it is a windows-related bug. since I do not have easy access to a windows machine, if you could conduct some testing it would be really great and speeding up the process.

for that, you would need to first clone this repository and be able to run it instead of `codedoc`. so for example, if you clone this repository to a folder next to your blog's repository, running it (from within your blog repository) would perhaps look something like `node ..\codedoc-cli\src\index.js check` (so `node ..\codedoc-cli\src\index.js` replaces `codedoc`).

if you can get that setup running, I highly suspect the source of the issue is [here](https://github.com/CONNECT-platform/codedoc-cli/blob/558f47f281d3931e284ef0eb68a2fcd590cdabf3/src/check/read-config.js#L9-L13). try for example changing those lines to:
```js
exec('ts-node', `-e 'console.log("hellow");'`)
```
and see what happens when you run check now.

**Comment by loreanvictor** [comment]
@bender2k14 nevermind, I did end up setting up a virtual box windows and finding the issue. will roll out an update now.

**Comment by loreanvictor** [comment]
deployed via `0.2.5`

**Comment by TysonMN** [comment]
Yep, that works.

Maybe some of this testing could be automated using GitHub Actions.

**Comment by loreanvictor** [comment]
> Maybe some of this testing could be automated using GitHub Actions.

Yes generally **CODEDOC** and all of its related projects are in dire need of proper automated testing. I am working on automated testing (and further optimization) for the underlying rendering library / markdown integration / pre-rendering library / etc., but due to my limited bandwidth I suspect it will take quite some time until I will reach **CODEDOC** or the CLI (which are naturally of lower priorities on that process since they are way higher up in the hierarchy).

**Comment by TysonMN** [comment]
For any of the CONNECT-platform repositories, if you create an issue about devops / automation and say what you want the behavior to be, then I might be able to contribute a PR with the desired behavior.

**Comment by loreanvictor** [comment]
> For any of the CONNECT-platform repositories, if you create an issue about devops / automation and say what you want the behavior to be, then I might be able to contribute a PR with the desired behavior.

If you have got the time, that would actually be great! I will start creating corresponding issues.
